// Code generated by wit-bindgen-go. DO NOT EDIT.

package types

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "jcbhmr:wajsi@0.1.0".

//go:wasmimport jcbhmr:wajsi/types@0.1.0 [resource-drop]object
//go:noescape
func wasmimport_ObjectResourceDrop(self0 uint32)

//go:wasmimport jcbhmr:wajsi/types@0.1.0 [method]object.clone
//go:noescape
func wasmimport_ObjectClone(self0 uint32) (result0 uint32)

//go:wasmimport jcbhmr:wajsi/types@0.1.0 [method]object.delete
//go:noescape
func wasmimport_ObjectDelete(self0 uint32, k0 uint32, k1 uint32, k2 uint32, result *cm.Result[ValueShape, bool, Value])

//go:wasmimport jcbhmr:wajsi/types@0.1.0 [method]object.get
//go:noescape
func wasmimport_ObjectGet(self0 uint32, k0 uint32, k1 uint32, k2 uint32, result *cm.Result[Value, Value, Value])

//go:wasmimport jcbhmr:wajsi/types@0.1.0 [method]object.has
//go:noescape
func wasmimport_ObjectHas(self0 uint32, k0 uint32, k1 uint32, k2 uint32, result *cm.Result[ValueShape, bool, Value])

//go:wasmimport jcbhmr:wajsi/types@0.1.0 [method]object.set
//go:noescape
func wasmimport_ObjectSet(self0 uint32, k0 uint32, k1 uint32, k2 uint32, v0 uint32, v1 uint64, v2 uint32, result *cm.Result[ValueShape, bool, Value])

//go:wasmimport jcbhmr:wajsi/types@0.1.0 [resource-drop]callable
//go:noescape
func wasmimport_CallableResourceDrop(self0 uint32)

//go:wasmimport jcbhmr:wajsi/types@0.1.0 [static]callable.downcast
//go:noescape
func wasmimport_CallableDowncast(o0 uint32, result *cm.Option[Callable])

//go:wasmimport jcbhmr:wajsi/types@0.1.0 [method]callable.call
//go:noescape
func wasmimport_CallableCall(self0 uint32, this0 uint32, this1 uint64, this2 uint32, args0 *Value, args1 uint32, result *cm.Result[Value, Value, Value])

//go:wasmimport jcbhmr:wajsi/types@0.1.0 [method]callable.clone
//go:noescape
func wasmimport_CallableClone(self0 uint32) (result0 uint32)

//go:wasmimport jcbhmr:wajsi/types@0.1.0 [method]callable.construct
//go:noescape
func wasmimport_CallableConstruct(self0 uint32, args0 *Value, args1 uint32, result *cm.Result[Value, Value, Value])

//go:wasmimport jcbhmr:wajsi/types@0.1.0 [method]callable.upcast
//go:noescape
func wasmimport_CallableUpcast(self0 uint32) (result0 uint32)

//go:wasmimport jcbhmr:wajsi/types@0.1.0 [resource-drop]symbol
//go:noescape
func wasmimport_SymbolResourceDrop(self0 uint32)

//go:wasmimport jcbhmr:wajsi/types@0.1.0 [method]symbol.clone
//go:noescape
func wasmimport_SymbolClone(self0 uint32) (result0 uint32)

//go:wasmimport jcbhmr:wajsi/types@0.1.0 [resource-drop]bigint
//go:noescape
func wasmimport_BigintResourceDrop(self0 uint32)

//go:wasmimport jcbhmr:wajsi/types@0.1.0 [method]bigint.clone
//go:noescape
func wasmimport_BigintClone(self0 uint32) (result0 uint32)

//go:wasmimport jcbhmr:wajsi/types@0.1.0 value-to-number
//go:noescape
func wasmimport_ValueToNumber(self0 uint32, self1 uint64, self2 uint32, result *cm.Result[ValueShape, float64, Value])

//go:wasmimport jcbhmr:wajsi/types@0.1.0 value-to-string
//go:noescape
func wasmimport_ValueToString(self0 uint32, self1 uint64, self2 uint32, result *cm.Result[ValueShape, string, Value])

//go:wasmimport jcbhmr:wajsi/types@0.1.0 value-to-boolean
//go:noescape
func wasmimport_ValueToBoolean(self0 uint32, self1 uint64, self2 uint32, result *cm.Result[ValueShape, bool, Value])

//go:wasmimport jcbhmr:wajsi/types@0.1.0 value-to-object
//go:noescape
func wasmimport_ValueToObject(self0 uint32, self1 uint64, self2 uint32, result *cm.Result[ValueShape, Object, Value])

//go:wasmimport jcbhmr:wajsi/types@0.1.0 value-instance-of
//go:noescape
func wasmimport_ValueInstanceOf(self0 uint32, self1 uint64, self2 uint32, c0 uint32, result *cm.Result[ValueShape, bool, Value])

//go:wasmimport jcbhmr:wajsi/types@0.1.0 value-loosely-equals
//go:noescape
func wasmimport_ValueLooselyEquals(self0 uint32, self1 uint64, self2 uint32, o0 uint32, o1 uint64, o2 uint32, result *cm.Result[ValueShape, bool, Value])

//go:wasmimport jcbhmr:wajsi/types@0.1.0 value-strictly-equals
//go:noescape
func wasmimport_ValueStrictlyEquals(self0 uint32, self1 uint64, self2 uint32, o0 uint32, o1 uint64, o2 uint32) (result0 uint32)

//go:wasmimport jcbhmr:wajsi/types@0.1.0 import
//go:noescape
func wasmimport_Import(s0 *uint8, s1 uint32, o0 uint32, o1 uint32, o2 uint64, o3 uint32, result *cm.Result[ValueShape, Object, Value])

//go:wasmimport jcbhmr:wajsi/types@0.1.0 get-import-meta
//go:noescape
func wasmimport_GetImportMeta(result *cm.Option[Object])

//go:wasmimport jcbhmr:wajsi/types@0.1.0 get-global-object
//go:noescape
func wasmimport_GetGlobalObject() (result0 uint32)
