package jcbhmr:ecmascript@16.0.0;

interface annex-b {
  use types.{
    string-object as types-string-object,
    reg-exp as types-reg-exp,
    date as types-date
  };

  escape: func(%string: string) -> string;
  unescape: func(%string: string) -> string;

  resource string-object {
    constructor(v: types-string-object);
    into-inner: static func(v: string-object) -> types-string-object;

    substr: func(start: s32, length: option<u32>);
    // ...
  }

  resource reg-exp {
    constructor(v: types-reg-exp);
    into-inner: static func(v: reg-exp) -> types-reg-exp;

    compile: func();
  }

  resource date {
    constructor(v: types-date);
    into-inner: static func(v: date) -> types-date;
  }
}