package jcbhmr:ecmascript-wasm@16.0.0;

interface shared-array-buffer {
    use type-error.{type-error};
    use range-error.{range-error};
    record constructor-options {
        max-byte-length: option<u32>,
    }
    variant grow-error {
        type-error(type-error),
        range-error(range-error),
    }
    resource shared-array-buffer {
        %constructor: static func(length: u32, options: option<constructor-options>) -> result<shared-array-buffer, range-error>;
        get-byte-length: func() -> u32;
        grow: func(new-length: u32) -> result<_, grow-error>;
        get-growable: func() -> bool;
        get-max-byte-length: func() -> u32;
        slice: func(start: s32, end: s32) -> shared-array-buffer;
    }
}